# Generated by Django 4.2.30 on 2026-07-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("friendships", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="friendship",
            index=models.Index(
                fields=["from_user", "status"], name="friendships_from_us_4e045a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="friendship",
            index=models.Index(
                fields=["to_user", "status"], name="friendships_to_user_80cd04_idx"
            ),
        ),
    ]
