# Generated by Django 4.2.30 on 2026-07-05 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_tag_post_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="shared_post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shares",
                to="posts.post",
            ),
        ),
    ]
