# Generated by Django 4.2.30 on 2026-07-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0005_poll_polloption_pollvote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="is_draft",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="post",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("friends", "Friends Only"),
                    ("only_me", "Only Me"),
                ],
                db_index=True,
                default="public",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["visibility", "is_draft", "-created_at"],
                name="posts_post_visibil_9180b7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="savedpost",
            index=models.Index(
                fields=["user", "-created_at"], name="posts_saved_user_id_2a11f0_idx"
            ),
        ),
    ]
