# Generated by Django 4.2.30 on 2026-07-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reactions", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="reaction",
            index=models.Index(
                fields=["post", "reaction_type"], name="reactions_r_post_id_36c0cb_idx"
            ),
        ),
    ]
