# Generated by Django 4.2.30 on 2026-07-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_customuser_is_email_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="last_seen",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
