# Generated by Django 4.2.30 on 2026-07-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation", "is_read", "-created_at"],
                name="messaging_m_convers_ef6ac2_idx",
            ),
        ),
    ]
